language: php

php:
    - '7.2'
    - '7.3'

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - $HOME/.composer/cache

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS yii2_basic_tests;'
    - mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root';FLUSH PRIVILEGES;"

install:
    - composer config github-oauth.github.com ${GH_TOKEN}
    - composer update --prefer-dist --no-interaction
    - php init --env=Development --overwrite=n
    - php tests/bin/yii migrate/up --interactive=0

script:
    - vendor/bin/codecept build
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no
    - vendor/bin/phpstan analyse -c phpstan.neon -l max .
    - vendor/bin/codecept run --coverage-xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
